# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IMTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IMTest
  
  pod 'GCDAsyncSocket'
  
  target 'IMTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
